HotelBookingSystem-Azure/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HotelBookingSystem_Azure.Models
{
    public class User
    {
        [Key]

        public int user_id { get; set; }

        public string password { get; set; }

        public string role { get; set; }

        public string user_name { get; set; }

        public int mobile_num { get; set; }

        public string address { get; set; }

        public string email { get; set; }
    }
}

HotelBookingSystem-Azure/Controllers/AdminController.cs
using HotelBookingSystem_Azure.Infrastructure;
using HotelBookingSystem_Azure.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelBookingSystem_Azure.Controllers
{
    public class AdminController : Controller
    {
        private readonly InterfaceHotelServices HotelServices;
        private readonly ILogger<AdminController>  _logger;
        private readonly SendServiceBusMessage _sendServiceBusMessage;

        public AdminController(InterfaceHotelServices HotelServices, ILogger<AdminController> logger , SendServiceBusMessage sendServiceBusMessage)
        {
            _logger = logger;
            _logger.LogInformation("HBS SYSTEM APP");
            this.HotelServices = HotelServices;
            _sendServiceBusMessage = sendServiceBusMessage;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Admin()
        {
            return View();
        }
        public async Task<IActionResult> HotelList()
        {
            _logger.LogInformation("HotelList endpoint starts");
            var Hotel = await HotelServices.HotelList();
            try
            {
                if (Hotel == null) return NotFound();
                _logger.LogInformation("HotelList endpoint completed");
            }
            catch (Exception ex)
            {
                _logger.LogError("exception occured;ExceptionDetail:" + ex.Message);
                _logger.LogError("exception occured;ExceptionDetail:" + ex.InnerException);
                _logger.LogError("exception occured;ExceptionDetail:" + ex);
                return BadRequest();
            }
            return View(Hotel);
        }

        public async Task<IActionResult> BookingRequestList()
        {
            _logger.LogInformation("Booking request list endpoint starts");
            var Request = await HotelServices.BookingRequestsList();
            try
            {
                if (Request == null) return NotFound();
                _logger.LogInformation("Booking request list endpoint  completed");
            }
            catch (Exception ex)
            {
                _logger.LogError("exception occured;ExceptionDetail:" + ex.Message);
                _logger.LogError("exception occured;ExceptionDetail:" + ex.InnerException);
                _logger.LogError("exception occured;ExceptionDetail:" + ex);
                return BadRequest();
            }
            return View(Request);
        }

        public async Task<IActionResult> Report()
        {
            _logger.LogInformation("Report endpoint starts");
            var report = await HotelServices.Report();
            try
            {
                if (report == null) return NotFound();
                _logger.LogInformation("Report endpoint completed");
            }
            catch (Exception ex)
            {
                _logger.LogError("exception occured;ExceptionDetail:" + ex.Message);
                _logger.LogError("exception occured;ExceptionDetail:" + ex.InnerException);
                _logger.LogError("exception occured;ExceptionDetail:" + ex);
                return BadRequest();
            }
            return View(report);
        }

        public IActionResult AddHotel()
        {
            return View();
        }

       
        [HttpPost]
        public async Task<IActionResult> AddHotel(Hotel hotel)
        {
            try
            {
                HotelServices.AddHotel(hotel);

            }
            catch (Exception e)
            {
                _logger.LogError("Exception Occured", e.InnerException);
            }
            ViewBag.Message = string.Format("Hotel Added Successfully");
            return View();

        }
       

        public IActionResult UpdateHotel()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UpdateHotel(Hotel hotel)
        {
            try
            {
                HotelServices.UpdateHotel(hotel);


            }
            catch (Exception e)
            {
                _logger.LogError("Exception Occured", e.InnerException);
            }
            ViewBag.Message = string.Format("updated hotel data Successfully");
            return View();

        }


    
        public IActionResult DeleteHotel()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> DeleteHotel(int hotel_id)
        {
            try
            {
                HotelServices.DeleteHotel(hotel_id);

            }
            catch (Exception e)
            {
                _logger.LogError("Exception Occured", e.InnerException);
            }
            ViewBag.Message = string.Format("Hotel Deleted Successfully");
            return View();
        }

        public IActionResult ApproveBooking()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> ApproveBooking(BookingDetails booking)
        {
            try
            {
                HotelServices.ApproveBooking(booking);

                await _sendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                {
                    booking_id = booking.booking_id,
                    room_id = booking.room_id,
                    user_id = booking.user_id,
                    Action = "Approved Booking"
                });

            }
            catch (Exception e)
            {
                _logger.LogError("Exception Occured", e.InnerException);
            }
            ViewBag.Message = string.Format("Booking Approved  Successfully");
            return View();

        }



    }
}

HotelBookingSystem-Azure/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using HotelBookingSystem_Azure.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace HotelBookingSystem_Azure.Controllers
{
    public class UploadController : Controller
    {
        public UploadFile _uploadFileToBlob;
        public UploadController(UploadFile uploadFileToBlob)
        {
            _uploadFileToBlob = uploadFileToBlob;
        }

        [Route("Upload/UploadFileAsync")]
        public IActionResult UploadFile()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UploadFileAsync1()
        {
            try
            {
                var formCollection = await Request.ReadFormAsync();
                var file = formCollection.Files.First();
                if (file.Length > 0)
                {
                    var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                    string fileURL = await _uploadFileToBlob.UploadFileToBlobAsync(file.OpenReadStream(), fileName, file.ContentType);
                    ViewBag.Message = string.Format("File Uploaded Successfully");
                    return View("UploadFile");
                }
                else
                {
                    return BadRequest();
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex}");
            }
        }
    }
}

HotelBookingSystem-Azure/Controllers/UserController.cs
using HotelBookingSystem_Azure.Infrastructure;
using HotelBookingSystem_Azure.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelBookingSystem_Azure.Controllers
{
    public class UserController : Controller
    {
        private readonly InterfaceHotelServices HotelServices;
        private readonly ILogger<UserController> _logger;
        private readonly SendServiceBusMessage _sendServiceBusMessage;

        public UserController(InterfaceHotelServices HotelServices, ILogger<UserController> logger , SendServiceBusMessage sendServiceBusMessage)
        {
            _logger = logger;
            _logger.LogInformation("HBS SYSTEM APP");
            this.HotelServices = HotelServices;
            _sendServiceBusMessage = sendServiceBusMessage;
        }
        public IActionResult User()
        {
            return View();
        }

        public IActionResult RegisterNewUser()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> RegisterNewUser(User user)
        {
            try
            {
                HotelServices.RegisterNewUser(user);

                await _sendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                {
                    user_name = user.user_name,
                    user_id = user.user_id,
                    Action = "Registered"
                });

            }
            catch (Exception e)
            {
                _logger.LogError("Exception Occured", e.InnerException);
            }
            ViewBag.Message = string.Format("User Added Successfully");
            return View();

        }

        public IActionResult AddBookingRequest()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> AddBookingRequest(BookingRequest booking)
        {
            try
            {
                HotelServices.AddBookingRequest(booking);

                await _sendServiceBusMessage.sendServiceBusMessage(new ServiceBusMessageData
                {
                    user_name = booking.user_name,
                    Booking_id = booking.Booking_id,
                    hotel_name = booking.hotel_name,
                    Action = "Requested For Booking"
                });

            }
            catch (Exception e)
            {
                _logger.LogError("Exception Occured", e.InnerException);
            }
            ViewBag.Message = string.Format("Booking Request Has Been Made Successfully");
            return View();

        }

        public async Task<IActionResult> HotelList()
        {
            _logger.LogInformation("HotelList endpoint starts");
            var Hotel = await HotelServices.HotelList();
            try
            {
                if (Hotel == null) return NotFound();
                _logger.LogInformation("HotelList endpoint completed");
            }
            catch (Exception ex)
            {
                _logger.LogError("exception occured;ExceptionDetail:" + ex.Message);
                _logger.LogError("exception occured;ExceptionDetail:" + ex.InnerException);
                _logger.LogError("exception occured;ExceptionDetail:" + ex);
                return BadRequest();
            }
            return View(Hotel);
        }
        public async Task<IActionResult> RoomList()
        {
            _logger.LogInformation("Room list endpoint starts");
            var Room = await HotelServices.RoomList();
            try
            {
                if (Room == null) return NotFound();
                _logger.LogInformation("Roomlist endpoint completed");
            }
            catch (Exception ex)
            {
                _logger.LogError("exception occured;ExceptionDetail:" + ex.Message);
                _logger.LogError("exception occured;ExceptionDetail:" + ex.InnerException);
                _logger.LogError("exception occured;ExceptionDetail:" + ex);
                return BadRequest();
            }
            return View(Room);
        }



    }
}

HotelBookingSystem-Azure/Views/User/AddBookingRequest.cshtml
@model HotelBookingSystem_Azure.Models.BookingRequest

@{ ViewData["Title"] = "Add Booking Request"; }

<form method="post" style="background-color:azure" asp-controller="User" asp-action="AddBookingRequest">
    <div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Booking_id"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Booking_id" class="form-control" />
                        <span asp-validation-for="Booking_id" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="hotel_name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="hotel_name" class="form-control" />
                        <span asp-validation-for="hotel_name" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="user_name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="user_name" class="form-control" />
                        <span asp-validation-for="user_name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="room_type"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="room_type" class="form-control" />
                        <span asp-validation-for="room_type" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="booked_from"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="booked_from" class="form-control" />
                        <span asp-validation-for="booked_from" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="booked_to"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="booked_to" class="form-control" />
                        <span asp-validation-for="booked_to" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="no_of_adults"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="no_of_adults" class="form-control" />
                        <span asp-validation-for="no_of_adults" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="no_of_children"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="no_of_children" class="form-control" />
                        <span asp-validation-for="no_of_children" class="text-danger"></span>
                    </div>
                </div>
                

               
                <div class="form-group row">

                    <div class="col-4 offset-4">
                        <input type="submit" class="btn btn-info w-100" value="Add" />
                    </div>
                    @if (ViewBag.Message != null)
                    {
        <a class="nav-link text-black-50 btn-outline-primary font-weight-bolder" style="position: relative; margin:10px;background-color: azure;float: right" asp-controller="Upload" asp-action="UploadFile"> Upload Supporting Document </a>
                        <script type="text/javascript">
                                      window.onload=function(){
                                          alert("@ViewBag.Message");
                                      };
                        </script>
}
                </div>
            </div>
        </div>
    </div>
</form>

HotelBookingSystem-Azure/Views/User/RegisterNewUser.cshtml
@model HotelBookingSystem_Azure.Models.User

@{ ViewData["Title"] = "Register New User"; }

<form method="post" style="background-color:azure" asp-controller="User" asp-action="RegisterNewUser">
    <div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="user_id"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="user_id" class="form-control" />
                        <span asp-validation-for="user_id" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="password"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="password" class="form-control" />
                        <span asp-validation-for="password" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="role"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="role" class="form-control" />
                        <span asp-validation-for="role" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="user_name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="user_name" class="form-control" />
                        <span asp-validation-for="user_name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="mobile_num"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="mobile_num" class="form-control" />
                        <span asp-validation-for="mobile_num" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="address"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="address" class="form-control" />
                        <span asp-validation-for="address" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="email"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="email" class="form-control" />
                        <span asp-validation-for="email" class="text-danger"></span>
                    </div>
                </div>
                

                <div class="form-group row">

                    <div class="col-4 offset-4">
                        <input type="submit" class="btn btn-info w-100" value="Register" />
                    </div>
                    @if (ViewBag.Message != null)
                    {
        <a class="nav-link text-black-50 btn-outline-primary font-weight-bolder" style="position: relative; margin:10px;background-color: beige;float: right" asp-controller="User" asp-action="AddBookingRequest">Add Booking request </a>
                        <script type="text/javascript">
                                      window.onload=function(){
                                          alert("@ViewBag.Message");
                                      };
                        </script>}
                </div>
            </div>
        </div>
    </div>
</form>

HotelBookingSystem-Azure/Views/User/RoomList.cshtml
@model IEnumerable<HotelBookingSystem_Azure.Models.RoomDetails>

@{
    ViewData["Title"] = "RoomList";
}


<div>
    <h2 class="text-primary">Room List</h2>
</div>

<div class="container p-3" style="background-color:azure">
    <

    <div>
        <a class="nav-link text-dark btn-primary font-weight-bold" style="margin: 10px; background-color: #00b9ff;float: right" asp-controller="User" asp- asp-action="RoomList">Room List</a>
    </div>
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        room_no
                    </th>
                    <th>
                        room_type
                    </th>
                    <th>
                        per_night_rate
                    </th>
                    <th>
                        availability
                    </th>
                    <th>
                        hotel_id
                    </th>
                    
                    <th>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var detail in Model)
                {
                    <tr>
                        <td>@detail.room_no</td>
                        <td>@detail.room_type</td>
                        <td>@detail.per_night_rate</td>
                        <td>@detail.availability</td>
                        <td>@detail.hotel_id</td>
                       

                    </tr>
                }
            </tbody>
        </table>
    }
</div>

HotelBookingSystem-Azure/Views/User/User.cshtml
@{
    ViewData["Title"] = "User";
}

<div class="text-center">
    <h1 class="display-4">Welcome To User Dashboard</h1>


    <div>

        <h2><a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: lightsteelblue; " asp-controller="Admin" asp-action="HotelList">Hotel List</a></h2>
        <h2><a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: lightsteelblue; " asp-controller="User" asp-action="RegisterNewUser">Register New User</a></h2>
        <h2><a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: lightsteelblue; " asp-controller="User" asp-action="RoomList">Room List</a></h2>
        <h2><a class="nav-link text-dark btn-primary font-weight-bold" style="position: relative; margin: 10px; background-color: lightsteelblue; " asp-controller="User" asp-action="AddBookingRequest">AdD Booking Request</a></h2>
        
    </div>
</div>